### ISSUE TITLE
Linker Error Ubuntu 11.10

### ISSUE THREAD

**Issue by woomia** [OpenCDE/opencde#17]
In trying to compile the latest OpenCDE I get:

```
make[2]: Entering directory `/home/chris/OpenCDE-opencde-e387c96/src/dtpanel'
g++ -o ../../bin/dtpanel main.o PanelWindow.o ExitDialog.o Grab.o MenuWindow.o -L../../lib -L/usr/X11R6/lib -L/usr/local/lib -lmotifmm -lopencde
/usr/bin/ld: PanelWindow.o: undefined reference to symbol 'XpmReadFileToPixmap'
/usr/bin/ld: note: 'XpmReadFileToPixmap' is defined in DSO /usr/lib/libXpm.so.4 so try adding it to the linker command line
/usr/lib/libXpm.so.4: could not read symbols: Invalid operation collect2: ld returned 1 exit status
make[2]: *** [../../bin/dtpanel] Error 1
make[2]: Leaving directory `/home/chris/OpenCDE-opencde-e387c96/src/dtpanel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/chris/OpenCDE-opencde-e387c96/src'
make: *** [all] Error 2
```

**Comment by woomia** [comment]
The file is indeed in /usr/lib/. Why isn't make finding it?

**Comment by arcfide** [comment]
It looks like your linker set is wrong. What does your Makefile look like?

**Comment by woomia** [comment]
I used used the make file that came in the tar ball.
On Mon, Jan 23, 2012 at 10:59 AM, arcfide <
reply@reply.github.com

**Comment by arcfide** [comment]
You should be running from the latest Git checkout. I've pushed a new branch ubuntu_build (d272700fd7f03fca6b803b44283a4f061462b2fc) that includes a simple fix. I think it should fix your issues, but could you please checkout that branch and try building vanilla? Let me know.

**Comment by woomia** [comment]
Will do.

On Mon, Jan 23, 2012 at 11:06 AM, arcfide <
reply@reply.github.com

**Comment by arcfide** [comment]
I have created a branch build_fixes that should fix both this build issue with Dtpanel as well as the build issue you mentioned out-of-band with Dtpad. Please let me know if this works.

**Comment by woomia** [comment]
I haven't seen a branch called build_fixes.
using make -lm still causes the build of dtpad to barf.

**Comment by arcfide** [comment]
On Tue, 24 Jan 2012 10:20:04 -0500, woomia  
reply@reply.github.com  
wrote:

> I haven't seen a branch called build_fixes.
> using make -lm still causes the build of dtpad to barf.

Please send me a tarball of your dtpad directory.

## 

Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us
לֵ֤ב חֲכָמִים֙ בְּבֵ֣ית אֵ֔בֶל וְלֵ֥ב כְּסִילִ֖ים בְּבֵ֥ית שִׂמְחָֽה

**Comment by woomia** [comment]
Its right from git. Nothing special.

On Wed, Jan 25, 2012 at 8:26 AM, arcfide <
reply@reply.github.com

**Comment by arcfide** [comment]
Can you please post the build log when building with this commit? c9ba4661cbd33f9beafa85e53398b9bc9d9adf16

**Comment by arcfide** [comment]
Fixed in build_fixes.
