### ISSUE TITLE
Build Error Log From Ubuntu 11.10 

### ISSUE THREAD

**Issue by woomia** [OpenCDE/opencde#19]
This is from the latest git, pulled AM 1/26

mkdir -p bin
cp script/\* bin/
make[1]: Entering directory `/root/opencde/src'
make[2]: Entering directory`/root/opencde/src/libmotifmm'
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Application.cpp -o Application.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Component.cpp -o Component.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Window.cpp -o Window.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude MessageBox.cpp -o MessageBox.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Panel.cpp -o Panel.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Button.cpp -o Button.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude ScrolledText.cpp -o ScrolledText.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Dialog.cpp -o Dialog.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Container.cpp -o Container.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Text.cpp -o Text.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Label.cpp -o Label.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Password.cpp -o Password.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude MenuBar.cpp -o MenuBar.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude PulldownMenu.cpp -o PulldownMenu.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Color.cpp -o Color.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude ToggleButton.cpp -o ToggleButton.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Custom.cpp -o Custom.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude IconButton.cpp -o IconButton.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Timer.cpp -o Timer.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude ScrolledPanel.cpp -o ScrolledPanel.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude ScrollBar.cpp -o ScrollBar.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude Separator.cpp -o Separator.o
g++ -shared -Wl,-soname,libmotifmm.so.2 -o ../../lib/libmotifmm.so.2.0.0 Application.o Component.o Window.o MessageBox.o Panel.o Button.o ScrolledText.o Dialog.o Container.o Text.o Label.o Password.o MenuBar.o PulldownMenu.o Color.o ToggleButton.o Custom.o IconButton.o Timer.o ScrolledPanel.o ScrollBar.o Separator.o -L/usr/X11R6/lib -L/usr/local/lib -lXpm -lXm -lXt -lX11
ln -s libmotifmm.so.2.0.0 ../../lib/libmotifmm.so.2
ln -s libmotifmm.so.2.0.0 ../../lib/libmotifmm.so
mkdir -p ../../include
cp -r include/\* ../../include
make[2]: Leaving directory `/root/opencde/src/libmotifmm'
make[2]: Entering directory`/root/opencde/src/libopencde'
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include Environment.cpp -o Environment.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include Shell.cpp -o Shell.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include Ini.cpp -o Ini.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include Filesystem.cpp -o Filesystem.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include ExceptionDialog.cpp -o ExceptionDialog.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include Workspace.cpp -o Workspace.o
g++ -Wall -Os -I/usr/X11R6/include -I/usr/local/include -fPIC -DPLATFORM_LINUX -DUSE_"" -c -Iinclude -I../../include vdesk.cpp -o vdesk.o
g++ -shared -Wl,-soname,libopencde.so.2 -o ../../lib/libopencde.so.2.0.0 Environment.o Shell.o Ini.o Filesystem.o ExceptionDialog.o Workspace.o vdesk.o -L/usr/X11R6/lib -L/usr/local/lib -lXpm -lXm -lXt -lX11
ln -s libopencde.so.2.0.0 ../../lib/libopencde.so.2
ln -s libopencde.so.2.0.0 ../../lib/libopencde.so
cp -r include/\* ../../include
make[2]: Leaving directory `/root/opencde/src/libopencde'
make[2]: Entering directory`/root/opencde/src/dtpad'
gcc   -Wall -Os -I/usr/X11R6/include -I/usr/local/include  -c -o utilities.o utilities.c
gcc   -Wall -Os -I/usr/X11R6/include -I/usr/local/include  -c -o main.o main.c
gcc   -Wall -Os -I/usr/X11R6/include -I/usr/local/include  -c -o creation.o creation.c
gcc   -Wall -Os -I/usr/X11R6/include -I/usr/local/include  -c -o callbacks.o callbacks.c
gcc   -Wall -Os -I/usr/X11R6/include -I/usr/local/include  -c -o bxutils.o bxutils.c
gcc   utilities.o main.o creation.o callbacks.o bxutils.o  -lXm -lXt -lSM -lICE -lXp -lXext -lX11 -o dtpad
make[2]: Leaving directory `/root/opencde/src/dtpad'
make[1]: Leaving directory`/root/opencde/src'
utilities.o: In function `long_to_string':
utilities.c:(.text+0x323): undefined reference to`log10'
utilities.c:(.text+0x32b): undefined reference to `floor'
collect2: ld returned 1 exit status
make[2]: **\* [dtpad] Error 1
make[1]: **\* [all] Error 2
make: **\* [all] Error 2

**Comment by woomia** [comment]
The build_fix branch solves this issue and OpenCDE (and DTpad) build on both Debian Squeeze and Ubuntu 11.10,

**Comment by arcfide** [comment]
build_fix has been merged into master now.
